#!/bin/bash

set -e
checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 2 1 2 "$@"
. /usr/local/otb/OTB-6.6.1-Linux64/otbenv.profile

set -x
python $BASEDIR/Evaluate_image_classification.py $INPUTS1 $INPUTS2 $PARAMS1 $OUTPUTS1 $OUTPUTS2

checkExitCode

