#!/bin/bash

set -e
checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 1 1 1 "$@"

set -x
python $BASEDIR/KML_to_Shapefile.py $INPUTS1 $PARAMS1 $OUTPUTS1

checkExitCode

