#!/bin/bash

set -e
checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 4 0 1 "$@"

set -x
python $BASEDIR/Merge_Shapefiles.py $INPUTS1 $INPUTS2 $INPUTS3 $INPUTS4 $OUTPUTS1

checkExitCode

